### ISSUE TITLE
Incorporate B_Raman_Test functionality into microscope

### ISSUE THREAD

**Issue by rowannicholls** [dop-oxford/microscope#3]
### Summary
@Alvaro-FG's [B_Raman_Test](https://github.com/Alvaro-FG/B_Raman_Test) repo contains working code that can be used with a B Raman controller that interfaces with an XY_stage, Z_stage, spectrometer and camera; potentially also an objective and tube lens. This code can be integrated into the `microscope` framework so as to consolidate the functionality that is available to users of both repos.

### Requirements
No additional requirements are desired per se - the functionality from the `B_Raman_Test` should be replicated

### User Stories
As a researcher working with microscopes, I want to be able to use a B Raman controller so that I can use a greater number of peripherals without writing new code myself.

### Acceptance Criteria:
- [ ] A B Raman controller must be usable via the `microscope` frontend
- [ ] An XY_stage, Z_stage, spectrometer, camera, objective and tube lens must be usable too as optional peripherals (ie their usage must be optional, this acceptance criteria is not optional)
- [ ] A simulated version of the functionality must be created
- [ ] Tests must be written for the functionality and these must be added to the CI
- [ ] Documentation must be written and added to the Sphinx docs

### Child Tickets
- [x] #1 
- [x] #5 
- [x] #6
- [x] #7 
- [x] #8
- [x] #9

**Comment by alasdairwilson** [comment]
To summarise discussion of meeting 22/07

If we initially change the base class of Alvaro's code from ABC to microscope.abc.Device the we can start porting over his classmethods to be overloads of the microscope abstractmethods.

This gives us an "in" to the microscope API.

There are two end-games here, neither of which are we sure are the desired outcome but we continue to keep them in mind as the end game and we can choose which we are happier with:

1. This code is integrated with Python-Microscope: Alvaros code can eventually just be importing his own device class from microscope and then configuring it.
2. The code is too "custom" to ever be part of the upstream project, it will continue to use PM as a dependency but live on as a separate entity with no upstream changes. This is still useful work because it allows us to use the cockpit api (see  #4 )

No need to make a call on this yet, we can see how the code works out.

**Comment by rowannicholls** [comment]
Closed; won't do
